[package]
name = "lotr-translation-update"
version = "0.1.0"
authors = ["AldanTanneo <aldantanneo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
dont_disappear = "3.0.1"
